[google_service_account]
type = "service_account"
project_id = "gen-lang-client-0700846098"
private_key_id = "c679a15f05009d15750e0476361e04760255963c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0OwKCIs+9YkG7
V408VLN7gXd69A9YPtosSPo4HAdQuM8uMmy15x8FjTL67dQ1yajZaBPn5K73A9yW
...
ZstAsYsdllrBvfB0WzJt7sM=
-----END PRIVATE KEY-----"""
client_email = "adhd-api@gen-lang-client-0700846098.iam.gserviceaccount.com"
client_id = "115796950104766560664"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/adhd-api%40gen-lang-client-0700846098.iam.gserviceaccount.com"
