[google_service_account]
type = "service_account"
project_id = "gen-lang-client-0700846098"
private_key_id = "c679a15f05009d15750e0476361e04760255963c"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC0OwKCIs+9YkG7
V408VLN7gXd69A9YPtosSPo4HAdQuM8uMmy15x8FjTL67dQ1yajZaBPn5K73A9yW
2JS/Jgdnau5fyVW68d/qN/AqXNIf9hk0rDd4ll7w9GchtZcOdrmEQFRg32sUNsDs
wf73iineR5LA2Uigizi64DF7Oe08aQTgxQFr6ofkpkhsGlVaqVa6olGn4mm0j4IP
cW92H/wDPgRHtVx3JgNP7hU8s9kKciwvQVztzSl/lJyxmjI+6JzcIOk9DQbLSq2f
p5hBk5nbLG6LiiLKG536xKal9XOuCKpvN4+crBDOatnZRtXPAB6Ng0d0xq8VHy94
sLMR5doXAgMBAAECggEAVQOOw9bq2eDas6VxPBeSD/x6YPd1s4D2RbRovwXNl5CN
PbPQXp92HRbFCOMdWf/VEzQKS7StqVvbdhYUV/P2wxwH9AvS0htcrS0Urs7Y2PWr
XxKrGckIYK1QZnCzH8H18UGs64MHjeHj7+n0PEyiQjTNrwTvQrdZG6E8Be3Fj1wJ
b5wxa5OfHRF93o6XA6rrV5brZMXWJedShxjJP+QVf98mu5KnYP9jUP/1+br1GSSP
elwbcm5sKoCbPJTzNhKLIpFhChq43ik6ChnqEc6qHEfOqZsoVtB4InYpZfdostnY
MXOOJYtNF8FIDi6G1D1ZNvBXI7TwzQLNKttgHVTl8QKBgQDhN/VmZk9OnsQ+C3CD
hPFKmrxsyFLscCKRrmdRF85Vr0X0xW3ut1KrSOGbVg+khuvl5MSY/DNAahKRIPAZ
OPJ62S/UytSJNEF93ftfnTwOoRjrA4CfRLGirffUML1N980lcIjW2x53Gp2RGXWz
3eNANLKZsmy3fpy2aSwQC/lycQKBgQDM3P1TXeh7OQAwS/LGtPrY7AsVvSeLcmHU
klF0M4kgTk68DsQRq3KRRrU79uf86cRFQ8dmrC90iRHJq5XBuzSIrjeJAgiRUzIc
RbmE97ovitW7irSHV9gjYaZNqxG5twXi2ehskYbjKxW96m5gGR4dgDuqrI8R8XLQ
3EUM0UnJBwKBgQCopnLJf4ub4CAsJfzXP9JAf6bh/xC5pS790I/lleIZH+tO5Bjy
Ta1GPolS/RsxpSc5PBpMRW9LqSLGMtgYyyApBkJfIpQNOmhgjL4UV3YFrnUuZ60F
lzc+DvAqoWTg4dNpWd/epK8nmXKsmVgenOXzyoKDvazTq6hGoHMygQUGwQKBgBac
5hGHshu35P9vwrKQU4gSNf8GTBEmZQoTxI3xClfYjPRRJO9WX2UNyv99d4oBO7rx
ilcY9nwEjUQXfoZN5bSYlmS3Jr7z0fow8BNvTMvmpUT4QIkX9zGgm7zC/0finfG2
X+NsBNmabeHyuJA+9YYIG43xUjGG10eaqLyLdXuNAoGATsEzwAtC0CPzEzzrJRvh
+GyvZ0W/At7NpBcEn7m/5Mjo+8sHzYVyY7Qkye3rO3X8Ek5tZhjA9I2xjXT3klhR
hoE+vX4lxResIJiPtosyrwhB3ad6bSw8uxG1/RvDGcLTVVPZ5E/a9gO5pNjnJBpw
ZstAsYsdllrBvfB0WzJt7sM=
-----END PRIVATE KEY-----"""
client_email = "adhd-api@gen-lang-client-0700846098.iam.gserviceaccount.com"
client_id = "115796950104766560664"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/adhd-api%40gen-lang-client-0700846098.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
